name: Sync to HuggingFace Hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.TO_HF_SPACES_TOKEN }}
        run: git push --force https://Arjuna17:$HF_TOKEN@huggingface.co/spaces/Arjuna17/basic-chat-bot main